<?php
global $text;
$text = array();
define('MENU_NAMES', 'Naslovna,Galerije,Forum,Blog,Dešavanja,Članovi,Upload,Kontakt');
define('MENU_LINKS', ',/galerije,/forum,/blog,/desavanja,/clan/lista,/galerije/upload,/korisnik/kontakt');
define('MENU_USER_NAMES', 'Opcije,Uredi profil,Pogledaj profil,Poruke,Moje galerije,Prijatelji,Omiljene slike,Odjava,E-full wall,Parovi,Drukanje');
$text['DAYS'] = 'Ponedeljak,Utorak,Sreda,Četvrtak,Petak,Subota,Nedelja';
$text['ERASE']='[obriši]';
$text['CHANGE']='[izmeni]';
$text['PAG_NUMBER']='Rezultata:';
$text['E_LOGIN_USERNAME']='Nije uneseno korisničko ime';
$text['E_LOGIN_PASSWORD']='Nije unesena lozinka';
$text['E_LOGIN_AUTHENTICATE']='Korisničko ime i lozinka se ne slažu';
$text['E_LOGIN_BLOCKED']='Vaš korisnički nalog je blokiran';
$text['USERNAME']='Korisničko ime';
$text['POSALJI']='Pošalji';
$text['PROMENI']='Promeni';
$text['WRONG_EMAIL']='Nepravilna email adresa';
$text['WRONG_USER']='Predugačko ili prekratko korisničko ime';
$text['WRONG_PASS']='Lozinka nije dobra ili nije dobro potvrđena';
$text['WRONG_USER2']='Postoji član sa tim korisničkim imenom';
$text['WRONG_EMAIL2']='Postoji član sa tom email adresom';
$text['WRONG_CAPTCHA']='Pogrešno unesen verifikacioni kod';
$text['REG_OK']='Registracija je uspela. Sada možete da se ulogujete.';
define('CALENDAR_MONTHS',',Jan,Feb,Mar,Apr,Maj,Jun,Jul,Avg,Sep,Okt,Nov,Dec');
define('CALENDAR_DAYS','pon,uto,sre,čet,pet,sub,ned');
define('KPREV','prošli');
define('KNEXT','sledeći');
define('WHO_ELSE_VISIT','[Ko još izlazi na ovo mesto?]');
define('CREW_VISIT',' Ekipa koja izlazi ovde...');
define('CREW_VISIT_NONE','Nema nikog u ekipi :(. Budi prvi :)');
define('CREW_VISIT_OPT','Hej, i ja ovde izlazim! :)@Ne, ja ovde više ne izlazim!');
define('MAX_ONLINE','<b>Maximalno online</b>  : %s , dana %s');
define('BIRTHDAY_USERS','<b>Rođendani : </b>');
define('TOTAL_USERS','<b>Ukupno članova : </b>');
define('NEWEST_USERS','<b>Najnoviji članovi : </b>');
define('ONLINE_USERS','<b>Trenutno on-line :</b> %s gostiju, %s članova'); 
define('UPDATES_PROFIL_HD','Promene');
define('UPDATES_PROFIL_MSGS','Nepročitane poruke: %s');
define('UPDATES_PROFIL_CMNTS','Komentara na profilu: %s');
define('UPDATES_PROFIL_PHOTO_CMNTS','Komentara za sliku: %s');
define('UPDATES_PROFIL_FRIENDS','Zahtevi za prijateljstvo: %s');
define('FORGOT_YOUR_PASSWORD','Zaboravili ste lozinku?');
define('USERNAME','Korisničko ime');
define('PASSWORD','Lozinka');
define('REGISTER','Registracija');
define('REMEMBER_ME','Zapamti me');
define('LOGIN','Prijavi se');
define('LAST_COMMENTS','Novi komentari');
define('RULES','Pravila');
define('SEND','Pošalji!');
define('ERASE','[Obriši]');
define('LOGIT','Korisničko ime ili email');

$text['TITLE']='Mesto za upoznavanje i druzenje, desavanja, slike i nocni provod ~ Extrafull';
$text['TITLE_photo']='Galerije i slike ~ Extrafull';
$text['TITLE_events']='Desavanja, koncerti, svirke, zurke ~ Extrafull';
$text['TITLE_forum']='Forum - diskusije i rasprave ~ Extrafull';
$text['TITLE_contact']='Kontakt ~ Extrafull';

$text['BLOCKUSER_MSG'] = 'Član te je blokirao! Verovatno si bio/la nevaljao. Popravi se malo ;)';
$text['DBERROR'] = 'Greška!';
$text['BLOCKING'] = '[blokiranje]';
$text['BLOCKME'] = 'Blokiraj člana';
$text['UNBLOCKME'] = 'Odblokiraj člana';
?>